// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20211108000107_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelApi.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Government Camp",
                            Country = "USA",
                            Description = "Giant Volcano east of Portland, OR",
                            Name = "Mt. Hood",
                            Rating = 10
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Grand Canyon Villge",
                            Country = "USA",
                            Description = "Large Desert Canyon in Arizona",
                            Name = "Grand Canyon",
                            Rating = 9
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Crater Lake",
                            Country = "USA",
                            Description = "Dormant Volcano with deep freshwater lake",
                            Name = "Crater Lake",
                            Rating = 7
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "White Salmon",
                            Country = "USA",
                            Description = "Put in for a really awesome section of whitewater kayaking",
                            Name = "Northwestern Park",
                            Rating = 8
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Austin",
                            Country = "USA",
                            Description = "Spring fed swimming hole in the middle of downtown Austin",
                            Name = "Barton Springs",
                            Rating = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
